version: '3'
services:
  webserver:
    user: "www-data"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./alice:/alice